language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

env:
    global:
    matrix:
        - CONTAO_VERSION=~3.1.0
        - CONTAO_VERSION=~3.2.0
        - CONTAO_VERSION=~3.3.0
        - CONTAO_VERSION=~3.4.0
        - CONTAO_VERSION=~3.5.0

install:
    - composer require contao/core $CONTAO_VERSION --prefer-dist --dev
    - composer install --prefer-dist --dev

script: ant -keep-going

branches:
  only:
    - tng
